"""Add job_description and generated_resume

Revision ID: 508d76bc1c4c
Revises: b555a1c75b7c
Create Date: 2026-07-29 10:06:45.918706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508d76bc1c4c'
down_revision: Union[str, Sequence[str], None] = 'b555a1c75b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('emails', sa.Column('generated_resume', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'generated_resume')
    op.drop_column('emails', 'job_description')
    # ### end Alembic commands ###
